---
- name: Initiate the Kubernetes Cluster
  command: 'kubeadm init --apiserver-advertise-address={{MASTER_IP}} --pod-network-cidr=192.168.0.0/16'
  register: output
- name: Display the logs
  debug:
    var: output.stdout
- name: Create a user
  user:
    name: '{{username}}'
    state: present
    password: "{{password|password_hash('sha512')}}"
- name: Create a file 
  file:
    path: '{{working_dir}}'
    state: directory
    mode: '0755'
    owner: '{{username}}'
    group: '{{username}}'
- name: Copy Kube-Configuration file
  copy:
    src: '{{Kube_Config_File}}'
    dest: '{{working_dir}}/config'
    mode: '0600'
    owner: '{{username}}'
    group: '{{username}}'
    remote_src: yes
# You can configure the Calico later 
# - name: Creat the Calico-Pod for CNI
#   become_user: '{{username}}'
#   command: 'kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml'
#   register: output
# - name: display the logs
#   debug:
#     var: output.stdout
# Execute the following command:
# kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/custom-resources.yaml

- name: Display the token
  command: 'kubeadm token create --print-join-command'
  register: output
- name: Display the token
  debug:
    var: output.stdout