---
- name: Install Containerization Tool
  yum:
    name: docker
    state: present
- name: Start the Docker Services
  service:
    name: docker
    enabled: true
    state: started
- name: Disable SELinux
  selinux:
    state: disabled
  when: 'ansible_selinux_python_present == true'
- name: Disable Firewall
  service:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true
- name: Disable the SWAP Memory
  command: 'swapoff -a'
- name: Disable SWAP in fstab 
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
- name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: 1
    state: present
- name: ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present