---
- hosts: demo
  become: yes
  tasks:
  - include_vars: vars.yml
  - name: Check the new disk details
    parted:
      device: '{{disk_name}}'
      number: 1
      state: present
      part_start: 1MiB
      part_end: "100%"
  - name: Convert into SWAP ID
    command: '{{item}}'
    with_items:
    - 'sfdisk --part-type {{disk_name}} 1 82'
    - 'mkswap {{part_name}}'
    - 'swapon {{part_name}}'
